"use client";
import {useEffect, useState} from 'react';
import {Asset, Document} from './project-types';

type Field = [string,string,number?];
const fields:Record<string,Field[]> = {
  Junction:[['elevation','Elevation (m)'],['emitter_coefficient','Emitter coefficient (SI)']],
  Reservoir:[['base_head','Total hydraulic head (m)']],
  Tank:[['elevation','Bottom elevation (m)'],['init_level','Initial level (m)'],['min_level','Minimum level (m)'],['max_level','Maximum level (m)'],['diameter','Tank diameter (m)'],['min_vol','Minimum volume (m³)']],
  Pipe:[['length','Hydraulic length (m)'],['diameter','Internal diameter (mm)',1000],['roughness','Roughness (selected formula)'],['minor_loss','Minor-loss coefficient']],
  Pump:[['power','Power (kW)',.001],['base_speed','Relative speed']],
  Valve:[['diameter','Diameter (mm)',1000],['minor_loss','Minor-loss coefficient']],
};
export default function AssetEditor({asset,type,document,onSave,onCancel}:{asset:Asset|null;type:string;document:Document;onSave:(a:Asset)=>void;onCancel:()=>void}) {
  const [draft,setDraft]=useState<Asset>({}); const [vertexText,setVertexText]=useState('[]'); const [demandText,setDemandText]=useState('[]'); const [error,setError]=useState('');
  const isNode=['Junction','Reservoir','Tank'].includes(type);
  useEffect(()=>{const d=asset?structuredClone(asset):{name:'',[isNode?'node_type':'link_type']:type, ...(type==='Pipe'?{vertices:[],minor_loss:0,initial_status:'Open'}:{}),...(type==='Valve'?{valve_type:'PRV',minor_loss:0,initial_status:'Active'}:{})};setDraft(d);setVertexText(JSON.stringify(d.vertices??[]));setDemandText(JSON.stringify((d.demand_timeseries_list??[]).map((v:Asset)=>({...v,base_val:v.base_val*1000})),null,2));setError('')},[asset,type,isNode]);
  function update(key:string,value:any){setDraft(d=>({...d,[key]:value}))}
  function submit(e:React.FormEvent){e.preventDefault();try{const next={...draft};if(type==='Pump'){next.pump_type=next.pump_curve_name?'HEAD':'POWER';if(next.pump_curve_name)next.power=null;}if(isNode&&next.coordinates?.every((v:any)=>v==null))delete next.coordinates;if(!next.name?.trim())throw Error('Enter an ID.');if(type==='Pipe'){next.vertices=JSON.parse(vertexText);if(!Array.isArray(next.vertices)||next.vertices.some((v:any)=>!Array.isArray(v)||v.length!==2||!v.every(Number.isFinite)))throw Error('Vertices must be pairs of numeric X/Y coordinates.');}if(type==='Junction'){const values=JSON.parse(demandText);if(!Array.isArray(values)||values.some((v:Asset)=>!Number.isFinite(v.base_val)))throw Error('Each demand category needs numeric base_val in L/s.');next.demand_timeseries_list=values.map((v:Asset)=>({...v,base_val:v.base_val/1000}));}onSave(next)}catch(err){setError(String(err))}}
  return <form className="asset-editor" onSubmit={submit}><h2>{asset?'Edit':'Add'} {type.toLowerCase()}</h2><label>ID<input required value={draft.name??''} disabled={!!asset} onChange={e=>update('name',e.target.value)}/></label>
    {isNode?<div className="pair">{['X / longitude','Y / latitude'].map((label,i)=><label key={label}>{label}<input type="number" step="any" value={draft.coordinates?.[i]??''} onChange={e=>{const coords=[...(draft.coordinates??[null,null])];coords[i]=e.target.value===''?null:Number(e.target.value);update('coordinates',coords)}}/></label>)}</div>:<div className="pair">{['start_node_name','end_node_name'].map((key,i)=><label key={key}>{i?'End / discharge node':'Start / suction node'}<select required value={draft[key]??''} onChange={e=>update(key,e.target.value)}><option value="">Choose node</option>{document.model.nodes.map(n=><option key={n.name} value={n.name}>{n.name} · {n.node_type}</option>)}</select></label>)}</div>}
    <div className="pair">{fields[type].map(([key,label,scale=1])=><label key={key}>{label}<input type="number" step="any" value={draft[key]==null?'':draft[key]*scale} onChange={e=>update(key,e.target.value===''?null:Number(e.target.value)/scale)}/></label>)}</div>
    {type==='Junction'&&<><label>Demand categories · base_val in L/s<textarea rows={7} value={demandText} onChange={e=>setDemandText(e.target.value)}/></label><button type="button" onClick={()=>{try{const d=JSON.parse(demandText);d.push({base_val:0,pattern_name:null,category:'Domestic'});setDemandText(JSON.stringify(d,null,2));}catch{setError('Correct the demand JSON first.')}}}>Add zero-demand category</button><small>Each category supports base_val, pattern_name and category. Zero demand is valid for a connection node.</small></>}
    {type==='Reservoir'&&<label>Head pattern<select value={draft.head_pattern_name??''} onChange={e=>update('head_pattern_name',e.target.value||null)}><option value="">Constant head</option>{document.model.patterns.map(p=><option key={p.name}>{p.name}</option>)}</select></label>}
    {type==='Tank'&&<><label>Volume curve<select value={draft.vol_curve_name??''} onChange={e=>update('vol_curve_name',e.target.value||null)}><option value="">Cylindrical</option>{document.model.curves.filter(c=>c.curve_type==='VOLUME').map(c=><option key={c.name}>{c.name}</option>)}</select></label><label>Overflow allowed<select value={String(draft.overflow??false)} onChange={e=>update('overflow',e.target.value==='true')}><option value="false">No</option><option value="true">Yes</option></select></label></>}
    {type==='Pump'&&<><label>Pump curve<select value={draft.pump_curve_name??''} onChange={e=>{update('pump_curve_name',e.target.value||null);update('pump_type',e.target.value?'HEAD':'POWER')}}><option value="">Use power rating</option>{document.model.curves.filter(c=>c.curve_type==='HEAD').map(c=><option key={c.name}>{c.name}</option>)}</select></label></>}
    {type==='Valve'&&<><label>Valve type<select value={draft.valve_type??'PRV'} onChange={e=>update('valve_type',e.target.value)}>{['PRV','PSV','PBV','FCV','TCV','GPV'].map(v=><option key={v}>{v}</option>)}</select></label><label>Setting ({draft.valve_type==='FCV'?'m³/s':draft.valve_type==='TCV'?'loss coefficient':draft.valve_type==='GPV'?'head-loss curve ID':'m pressure head'})<input value={draft.initial_setting??''} onChange={e=>update('initial_setting',draft.valve_type==='GPV'?e.target.value:Number(e.target.value))}/></label></>}
    {!isNode&&<label>Initial status<select value={draft.initial_status??'Open'} onChange={e=>update('initial_status',e.target.value)}>{['Open','Closed',...(type==='Valve'?['Active']:[])].map(s=><option key={s}>{s}</option>)}</select></label>}
    {type==='Pipe'&&<><label>Lock pipe diameter and connections<select value={String(draft.locked??false)} onChange={e=>update('locked',e.target.value==='true')}><option value="false">Editable</option><option value="true">Locked</option></select></label><label>Check valve<select value={String(draft.check_valve??false)} onChange={e=>update('check_valve',e.target.value==='true')}><option value="false">No · flow may reverse</option><option value="true">Yes · start to end only</option></select></label><label>Intermediate vertices · [[x,y], …]<textarea value={vertexText} onChange={e=>setVertexText(e.target.value)} rows={4}/></label><p className="hint">Bends change route geometry. They do not add hydraulic junctions.</p><div className="pair"><label>Road ID<input value={draft.road_id??''} onChange={e=>update('road_id',e.target.value)}/></label><label>Physical run ID<input value={draft.run_id??''} onChange={e=>update('run_id',e.target.value)}/></label></div></>}
    {error&&<p role="alert" className="error">{error}</p>}<div className="actions"><button className="primary" type="submit">Apply to draft</button><button type="button" onClick={onCancel}>Cancel</button></div></form>
}
