"use client";
import {useState} from 'react';
import {Document,Project,json,request} from './project-types';
export default function GeometryTools({project,doc,dirty,onChange,task}:{project:Project;doc:Document;dirty:boolean;onChange:(d:Document)=>void;task:(fn:()=>Promise<void>)=>Promise<void>}){
  const [action,setAction]=useState('roadside'),[layer,setLayer]=useState(''),[sides,setSides]=useState(2),[offset,setOffset]=useState(4),[diameter,setDiameter]=useState(100),[roughness,setRoughness]=useState(130);
  const [keep,setKeep]=useState(''),[remove,setRemove]=useState(''),[reason,setReason]=useState(''),[mode,setMode]=useState('replace');
  const junctions=doc.model.nodes.filter(n=>n.node_type==='Junction');
  async function preview(){await task(async()=>{if(dirty)throw Error('Save your current draft before creating a geometry preview.');if(action!=='join'&&layer==='')throw Error('Select an input layer.');const result=await request(`/projects/${project.id}/geometry-preview`,json('POST',{revision:project.revision,action,layer_index:Number(layer),sides,offset_m:offset,diameter_mm:diameter,roughness,keep,remove,reason,mode}));onChange(result.document)})}
  return <details className="geometry-tools"><summary>Road runs, physical connections and household allocation</summary><div className="card"><label>Action<select value={action} onChange={e=>{setAction(e.target.value);setLayer('')}}><option value="roadside">Create roadside candidate</option><option value="join">Join two junctions at one physical connection</option><option value="households">Allocate household demand</option></select></label>{action!=='join'?<label>Input layer<select value={layer} onChange={e=>setLayer(e.target.value)}><option value="">Choose layer</option>{doc.layers.map((l,i)=>l.role===(action==='roadside'?'roads':'households')?<option key={i} value={i}>{l.name}</option>:null)}</select></label>:<><div className="pair">{[[keep,setKeep,'Keep junction'],[remove,setRemove,'Merge junction']] .map(([value,setter,label]:any)=><label key={label}>{label}<select value={value} onChange={e=>setter(e.target.value)}><option value="">Choose junction</option>{junctions.map(n=><option key={n.name}>{n.name}</option>)}</select></label>)}</div><label>Field-approved physical connection / reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label><p className="notice">Use only for one physical connection. Opposite roadside runs require an explicit crossing pipe. Surviving coordinates and existing hydraulic lengths are retained for review.</p></>}
    {action==='roadside'&&<><div className="pair"><label>Longitudinal runs<select value={sides} onChange={e=>setSides(Number(e.target.value))}><option value={1}>One side</option><option value={2}>Both sides</option></select></label><label>Offset from centerline (m)<input type="number" value={offset} onChange={e=>setOffset(Number(e.target.value))}/></label><label>Candidate internal diameter (mm)<input type="number" value={diameter} onChange={e=>setDiameter(Number(e.target.value))}/></label><label>Candidate H-W roughness<input type="number" value={roughness} onChange={e=>setRoughness(Number(e.target.value))}/></label></div><p>Geometry uses a metric working CRS. Road IDs come from road_id. Optional start_elevation_m/end_elevation_m are retained; missing elevations require survey entry. No intersections or source connections are silently created.</p></>}
    {action==='households'&&<><label>Demand treatment<select value={mode} onChange={e=>setMode(e.target.value)}><option value="replace">Replace demands at explicitly assigned junctions</option><option value="add">Add to existing demands</option></select></label><p>Every household needs node_id and demand_lps. Population alone does not imply an assumed consumption rate. A layer can be allocated once.</p></>}
    <button disabled={dirty} onClick={preview}>Create editable preview</button><small>Review the resulting draft in the network map, then Save revision. Existing saved input remains recoverable.</small></div></details>
}
