"use client";
import {useState} from 'react';
import {API,Asset,Document,Issue,Project,json,request} from './project-types';
import {IssueList,ResultTable} from './Tables';
export default function InputPanel({project,doc,dirty,onChange,onImported,task}:{project:Project;doc:Document;dirty:boolean;onChange:(d:Document)=>void;onImported:(p:Project)=>void;task:(fn:()=>Promise<void>)=>Promise<void>}){
  const [file,setFile]=useState<File|null>(null),[role,setRole]=useState('network'),[crs,setCrs]=useState(''),[layer,setLayer]=useState(''),[mapping,setMapping]=useState<Record<string,string>>({}),[preview,setPreview]=useState<Asset|null>(null),[mappingDirty,setMappingDirty]=useState(false),[corrections,setCorrections]=useState<Record<string,Record<string,string>>>({});
  const roles=['network','junctions','reservoirs','tanks','pipes','households','roads','crossings','reference'];
  const targetFields:Record<string,string[]>={junctions:['name','x','y','elevation_m','demand_lps','pattern'],reservoirs:['name','x','y','head_m','pattern'],tanks:['name','x','y','elevation_m','initial_level_m','min_level_m','max_level_m','diameter_m'],pipes:['name','from_node','to_node','length_m','diameter_mm','roughness','status'],households:['household_id','longitude','latitude','population','node_id','demand_lps']};
  async function inspect(){await task(async()=>{if(!file)throw Error('Choose a file.');if(dirty)throw Error('Save your draft before previewing an import.');const form=new FormData();form.append('file',file);form.append('role',role);form.append('crs',crs);form.append('layer',layer);form.append('mapping',JSON.stringify(mapping));form.append('corrections',JSON.stringify(corrections));setPreview(await request(`/projects/${project.id}/imports`,{method:'POST',body:form}));setMappingDirty(false)})}
  return <section className="panel wide"><h2>Input library</h2><div className="input-grid"><div className="card"><h3>Upload and review</h3><label>File<input type="file" accept=".inp,.csv,.xlsx,.geojson,.json,.gpkg,.zip" onChange={e=>{setFile(e.target.files?.[0]??null);setPreview(null);setMapping({});setCorrections({})}}/></label><label>Data role<select value={role} onChange={e=>{setRole(e.target.value);setPreview(null)}}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><div className="pair"><label>Source CRS (if known)<input placeholder="EPSG:32646" value={crs} onChange={e=>{setCrs(e.target.value);setMappingDirty(true)}}/></label><label>GeoPackage layer (optional)<input value={layer} onChange={e=>{setLayer(e.target.value);setMappingDirty(true)}}/></label></div><button className="primary" onClick={inspect}>Preview upload</button><p className="hint">INP replaces the hydraulic model after review. Tables append assets; GIS uploads retain reference geometry. Maximum upload: 20 MB.</p><div className="actions">{['junctions','reservoirs','tanks','pipes','households'].map(r=><a key={r} href={`${API}/projects/templates/${r}`}>{r} template</a>)}</div></div><div className="card"><h3>Project spatial reference</h3><label>Network CRS<input value={doc.crs??''} placeholder="Blank = schematic coordinates" onChange={e=>onChange({...doc,crs:e.target.value||null})}/></label><p>Assign only a known CRS. Changing this label does not transform existing coordinates. Hydraulic lengths remain explicitly entered.</p><h3>Reference layers</h3>{doc.layers.length?doc.layers.map((l,i)=><p key={i}><b>{l.name}</b> · {l.role} · {l.data?.features?.length??0} features · {l.crs}</p>):<p>No field layers uploaded.</p>}<h3>Provenance</h3>{doc.provenance.map((p,i)=><p key={i}>{p.filename} · SHA-256 {p.sha256?.slice(0,12)}</p>)}</div></div>
    {preview&&<div className="card"><h3>Import preview · {preview.filename}</h3>{preview.notes.map((n:string,i:number)=><p key={i}>{n}</p>)}{targetFields[role]&&preview.columns.length>0&&<><h4>Column mapping</h4><div className="mapping-grid">{targetFields[role].map(f=><label key={f}>{f}<select value={mapping[f]??f} onChange={e=>{setMapping(m=>({...m,[f]:e.target.value}));setMappingDirty(true)}}><option value={f}>{f} (default)</option>{preview.columns.filter((c:string)=>c!==f).map((c:string)=><option key={c}>{c}</option>)}</select></label>)}</div><button onClick={inspect}>Re-preview with mapping</button></>}{targetFields[role]?<div className="table-scroll"><table><thead><tr>{preview.columns.map((c:string)=><th key={c}>{c}</th>)}</tr></thead><tbody>{preview.rows.map((row:Asset,i:number)=><tr key={i}>{preview.columns.map((c:string)=><td key={c}><input aria-label={`Row ${i+2} ${c}`} value={corrections[i]?.[c]??row[c]??''} onChange={e=>{setCorrections(old=>({...old,[i]:{...old[i],[c]:e.target.value}}));setMappingDirty(true)}}/></td>)}</tr>)}</tbody></table><small>Edit the preview rows, then re-preview to validate corrections. The original upload is retained.</small></div>:<ResultTable rows={preview.rows} fields={preview.columns}/>}<IssueList issues={preview.issues}/><button className="primary" disabled={dirty||mappingDirty||preview.revision!==project.revision||preview.issues.some((i:Issue)=>i.rule==='IMPORT_ROW')} onClick={()=>task(async()=>{const p=await request(`/projects/${project.id}/imports/${preview.id}/commit`,json('POST',{revision:project.revision}));onImported(p);setPreview(null)})}>Commit preview as draft revision</button><small>Incomplete models may be saved for editing. Invalid table rows must be corrected before commit. Re-preview after changing mapping or CRS.</small></div>}
  </section>
}
