"use client";
import {useMemo,useState} from 'react';
import {Asset,Document} from './project-types';

export default function NetworkView({document,selected,onSelect,values={}}:{document:Document;selected?:string;onSelect:(a:Asset)=>void;values?:Record<string,number>}){
  const [zoom,setZoom]=useState(1);
  const geometry=useMemo(()=>{const nodes=document.model.nodes.filter(n=>Array.isArray(n.coordinates)&&n.coordinates.length===2&&n.coordinates.every(Number.isFinite));const byId=new Map(nodes.map(n=>[n.name,n]));const links=document.model.links.filter(l=>byId.has(l.start_node_name)&&byId.has(l.end_node_name)).map((l):Asset=>({...l,points:[byId.get(l.start_node_name)!.coordinates,...(l.vertices??[]),byId.get(l.end_node_name)!.coordinates]}));const points=[...nodes.map(n=>n.coordinates),...links.flatMap(l=>l.points)].filter(p=>p.every(Number.isFinite));if(!points.length)return null;const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);const xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);const scale=Math.min(820/(xmax-xmin||1),460/(ymax-ymin||1));return {nodes,links,x:(v:number)=>50+(v-xmin)*scale,y:(v:number)=>510-(v-ymin)*scale}},[document]);
  if(!geometry)return <div className="empty-map">Add node coordinates or import a network to see its layout.<br/>Hydraulic connectivity comes from endpoint IDs.</div>;
  const {nodes,links,x,y}=geometry;
  return <div className="network-view"><div className="map-tools"><span>{document.crs??'Schematic · no CRS'} · {nodes.length} located nodes</span><button onClick={()=>setZoom(z=>Math.min(4,z+.25))}>Zoom +</button><button onClick={()=>setZoom(z=>Math.max(.5,z-.25))}>Zoom −</button><button onClick={()=>setZoom(1)}>Fit</button></div><div className="svg-scroll"><svg viewBox="0 0 920 560" style={{width:`${zoom*100}%`,minHeight:450}} role="img" aria-label="Hydraulic network with full pipe geometry"><rect width="920" height="560" fill="#eef2eb"/>{links.map(l=><g key={l.name}><polyline role="button" tabIndex={0} aria-label={`Select ${l.link_type} ${l.name}`} points={l.points.map((p:number[])=>`${x(p[0])},${y(p[1])}`).join(' ')} fill="none" stroke={selected===l.name?'#d8821d':'#087d83'} strokeWidth={selected===l.name?5:3} onClick={()=>onSelect(l)} onKeyDown={e=>{if(e.key==='Enter')onSelect(l)}}/><title>{l.name} · {l.link_type}</title></g>)}{nodes.map(n=><g key={n.name} role="button" tabIndex={0} aria-label={`Select ${n.node_type} ${n.name}`} onClick={()=>onSelect(n)} onKeyDown={e=>{if(e.key==='Enter')onSelect(n)}}>{n.node_type==='Junction'?<circle cx={x(n.coordinates[0])} cy={y(n.coordinates[1])} r={selected===n.name?8:5} fill={values[n.name]!=null&&values[n.name]<=document.criteria.minimum_pressure_m?'#ba3535':'#17324d'} stroke="white" strokeWidth="2"/>:<rect x={x(n.coordinates[0])-7} y={y(n.coordinates[1])-7} width="14" height="14" fill={n.node_type==='Tank'?'#9a5cab':'#17613d'} stroke="white"/>}<text x={x(n.coordinates[0])+9} y={y(n.coordinates[1])-9} fontSize="11" fill="#17324d">{n.name}{values[n.name]!=null?` · ${values[n.name].toFixed(1)} m`:''}</text></g>)}</svg></div><small>Circles: junctions · Squares: reservoir/tank · Intermediate bends have no node symbol. Click a pipe or node to inspect.</small></div>
}
